#!/usr/bin/env bash
# Script: vzf
# Description: Fuzzy-find a file (avoiding system-protected directories), then open it in vim

search_dirs=(~ ~/Documents ~/Downloads ~/dev ~/Desktop ~/productivity)

# selected_file=$(find "${search_dirs[@]}" -type f 2>/dev/null | fzf --height 40% --preview 'bat --style=numbers --color=always {} 2>/dev/null' --preview-window=right:60%)@
selected=$(find "${search_dirs[@]}" \( -type f -o -type d \) 2>/dev/null | fzf --height 40% --preview 'bat --style=numbers --color=always {} 2>/dev/null || ls -la {}' --preview-window=right:60%)

# selected_file=$(fzf --height 40% --preview 'bat --style=numbers --color=always {} 2>/dev/null' --preview-window=right:60%)
# selected_file=$(find . -type f \( ! -path "*/\.git/*" \) | fzf --height 40% --preview 'bat --style=numbers --color=always {} 2>/dev/null' --preview-window=right:60%)

if [ -n "$selected_file" ]; then
  vim "$selected_file"
fi
